name: Commits
on:
  - pull_request

permissions:
  contents: read

jobs:
  commit-checks:
    permissions:
      pull-requests: read  # to get list of commits from the PR
    runs-on: ubuntu-22.04
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Signed-off-by (DCO)
      uses: tim-actions/dco@master
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}

    - name: Check branch target
      env:
        TARGET: ${{ github.event.pull_request.base.ref }}
      run: |
        set -x
        [ "${TARGET}" = "latest-edge" ] && exit 0

        echo "Invalid branch target: ${TARGET}"
        exit 1
